# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0

stages:
  - lint
  - build
  - test
  - coverage
  - release
  - docs
  - configure
  - deploy

# https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
.if-default-branch-refs: &if-default-branch-refs
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.if-tag: &if-tag
  if: '$CI_COMMIT_TAG'

.if-merge-request: &if-merge-request
  if: '$CI_MERGE_REQUEST_IID'

# Workflow
###########
workflow:
  rules:
    - <<: *if-tag
      variables:
        # Override the IMAGE_SHA variable on tag pipelines to avoid both the default
        # branch pipeline and tag pipeline overriding each other's images arbitrarily when
        # they are both running at the same time on master.
        IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - <<: *if-default-branch-refs
    - <<: *if-merge-request


include:
  - project: 'labs/salt-automation'
    file:
      - '/gitlab-ci-templates/common/rules.v1.yml'
      - '/gitlab-ci-templates/common/saltbert.v1.yml'
      - '/gitlab-ci-templates/common/docker-build.v1.yml'
      - '/gitlab-ci-templates/common/docker-release-meta.v1.yml'
      - '/gitlab-ci-templates/common/config-updater-meta.v1.yml'
      - "/gitlab-ci-templates/common/conventional-commits-meta.v1.yml"
      - "/gitlab-ci-templates/common/conventional-commits-changelog-meta.v1.yml"

.releaserc:
  before_script:
    - |
      cat <<EOF > .releaserc.yaml
      branches:
        - master
      tagFormat: "\${version}-rc1"
      plugins:
        - - "@semantic-release/commit-analyzer"
          - preset: angular
            releaseRules:
              - type: chore
                scope: deps-dev
                release: patch
              - type: chore
                scope: deps
                release: patch
              - type: build
                scope: deps-dev
                release: patch
              - type: build
                scope: deps
                release: patch
        - "@semantic-release/release-notes-generator"
        - "@semantic-release/changelog"
        - - "@semantic-release/gitlab"
          - assets:
              - path: CHANGELOG.md
                label: Changelog
      EOF


variables:
  # Project variables
  RELEASE_REGISTRY: docker.io
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/dysleksi

  IMAGE_SHA: ${CI_REGISTRY_IMAGE}/dysleksi:${CI_COMMIT_SHA}
  IMAGE_TAG: magentaaps/dysleksi:${CI_COMMIT_TAG}

  VERSION: PIPELINE

  DOCKERFILE: $CI_PROJECT_DIR/docker/Dockerfile


# Lint stage
#############
.lint-default: &lint-default
  stage: lint
  needs: []
  image: python:3.14

Lint Commits:
  extends: .lint:commits
  variables:
    CONFIG: '{ extends: [''@commitlint/config-conventional''], ignores: [(message) => message.includes(''suggestion(s)'')], }'


Lint Python:
  <<: *lint-default
  before_script:
    - pip3 install flake8
    - pip3 install flake8-absolute-import
    - pip3 install black==24.4.1
    - pip3 install isort==5.13.2
    #- pip3 install -r django/requirements.txt
  script:
    - flake8 --max-line-length 88 --exclude=migrations,settings --extend-ignore E226,E203 dysleksi/ --
    - black --check --diff --exclude=migrations dysleksi/
    - isort -c --profile black --diff --skip migrations dysleksi/


Lint Dockerfiles:
  <<: *lint-default
  image: hadolint/hadolint:v2.14.0-debian
  before_script:
    - apt-get -y update
    - apt-get -y install --no-install-recommends git
  script:
    - git ls-files --exclude='Dockerfile*' --ignored --cached | xargs --max-lines=1 hadolint

Lint REUSE compliance:
  extends: .lint-default
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint

Lint Javascript:
  extends: .lint-default
  image: registry.gitlab.com/pipeline-components/eslint:latest
  script:
    - sh -c "cp .eslint/package.json package.json && npm install @eslint/js && eslint --config .eslint/eslint.config.js --color --stats dysleksi/dysleksi/static/dysleksi/*.js || rm package.json"

# Test stage
############
.test-default: &test-default
  stage: test
  dependencies: []
  needs: [ "Build" ]
  services:
    - name: postgres:18
      alias: dysleksi-db
    - name: redis:8
      alias: dysleksi-redis
  variables:
    # Simulate development environment while running tests so we use mockup data
    DJANGO_SECRET_KEY: 1DqtQVSbLLmgBvkhPyptqFwPpJE9Kkgdo2kZFZ57UnzuRMiFgw
    TZ: Europe/Copenhagen
    HOST_DOMAIN: https://localhost:8443
    POSTGRES_USER: dysleksi
    POSTGRES_PASSWORD: dysleksi
    POSTGRES_DB: dysleksi
    POSTGRES_HOST: dysleksi-db
    ENVIRONMENT: development
    ALLOWED_HOSTS: '["dysleksi-web", "localhost", "host.docker.internal"]'
    DUMMY_DATA_DIR: /builds/gronlandsprojekter/dysleksi/dummy-data
    REAL_DATA_DIR: /builds/gronlandsprojekter/dysleksi/real-data

    # Local SAML configuration
    SAML_SP_ENTITY_ID: https://localhost:8443/mitid/saml/metadata/
    SAML_SP_LOGIN_CALLBACK_URI: https://localhost:8443/mitid/login/callback/
    SAML_SP_LOGOUT_CALLBACK_URI: https://localhost:8443/mitid/logout/callback/
    SAML_SP_KEY: /ssl/sp/selfsigned.key
    SAML_SP_CERTIFICATE: /ssl/sp/selfsigned.crt
    SAML_IDP_ENTITY_ID: http://localhost:8080/simplesaml/saml2/idp/metadata.php
    SAML_IDP_LOGIN_URI: http://localhost:8080/simplesaml/saml2/idp/SSOService.php
    SAML_IDP_LOGOUT_URI: http://localhost:8080/simplesaml/saml2/idp/SingleLogoutService.php
    SAML_IDP_CERTIFICATE: /ssl/idp/selfsigned.crt
    SAML_IDP_METADATA: http://localhost:8080/simplesaml/saml2/idp/metadata.php
    SAML_CONTACT_TECHNICAL_NAME: Tester
    SAML_CONTACT_TECHNICAL_EMAIL: test@example.com
    SAML_CONTACT_SUPPORT_NAME: Tester
    SAML_CONTACT_SUPPORT_EMAIL: test@example.com
    SESSION_EXPIRE_SECONDS: 3600
    LOGIN_PROVIDER_CLASS: django_mitid_auth.saml.oiosaml.OIOSaml
    CREATE_DUMMY_USERS: True
    BYPASS_2FA: 'True'
    MEDIA_ROOT: /builds/gronlandsprojekter/dysleksi/file-data

  image: ${IMAGE_SHA}
  before_script:
    - mkdir "${CI_PROJECT_DIR}/coverage_output"
  artifacts:
    when: always
    paths:
      - "coverage_output/*"
    expire_in: 1 day

Python Unittest:
  <<: *test-default
  script:
    - cd /app
    - coverage run manage.py test --parallel
    - coverage combine
    - coverage report --show-missing --fail-under=99
    - coverage xml -o /app/coverage.xml
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: /app/coverage.xml

Mypy:
  <<: *test-default
  script:
    - cd /app
    - mypy --config mypy.ini ./

Django check:
  <<: *test-default
  script:
    - cd /app
    - python manage.py check dysleksi


Javascript Unittest:
  stage: test
  needs: []
  image: node:25
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - node_modules/
  before_script:
    - cd dysleksi
    - npm ci
  script:
    - |
      npx vitest run \
        --coverage \
        --coverage.thresholds.statements=88.51 \
        --coverage.thresholds.branches=86.13 \
        --coverage.thresholds.functions=85.52 \
        --coverage.thresholds.lines=88.49 \
        --coverage.provider=istanbul \
        --coverage.include="dysleksi/static/js/**/*.js" \
        --coverage.exclude="dysleksi/static/js/__tests__/**/*.js" \
      2>&1 | tee vitest_output.txt
    - awk -F'|' '/All files/ {sum=0; for(i=2;i<=5;i++){gsub(/ /,"",$i); sum+=$i} printf "Average coverage = %.2f%%\n", sum/4}' vitest_output.txt
  coverage: '/Average coverage = ([0-9]+\.[0-9]+)%/'


# Release stage
###############

Release image:
  stage: release
  image: alpine
  variables:
    GIT_STRATEGY: none # We do not need the source code
  dependencies: []
  before_script:
    # install skopeo
    - apk add skopeo
  # Releases both stable and RC releases.
  extends:
    - .rules:semver-all
  needs:
    ["Build", "Python Unittest", "Javascript Unittest", "Django check", "Mypy"]
  script:
    - skopeo copy
      --src-creds=${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}
      --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
      "docker://${IMAGE_SHA}"
      "docker://${IMAGE_TAG}"


Release Semantic commit:
  extends: .release:semantic-commit

Release Generate changelog:
  extends: .release:generate-changelog

Docs Export changelog:
  extends:
    - .rules:semver-all
    - .docs:export-changelog
  variables:
    CHANGELOG_EXTRA_FLAGS: "--merge-prerelease"


# Configure stage
#################

Configure Test:
  stage: configure
  extends:
    - .rules:semver-all
    - .config:endpoint-with-tag
  needs: ["Release image"]
  variables:
    ENDPOINT: dysleksi/salt/update-test

Configure Production:
  stage: configure
  extends:
    - .rules:semver-core
    - .config:endpoint-with-tag
  needs: ["Release image"]
  variables:
    ENDPOINT: dysleksi/salt/update-production

# Deploy stage
##############

Deploy to Test:
  stage: deploy
  extends:
    - .rules:semver-all
    - .saltbert
  needs: [ "Configure Test" ]
  variables:
    SALTBERT_ORCHESTRATION: groenland.dysleksi.service-test
    SALTBERT_URL: https://saltmaster.groenland.magentahosted.dk
  rules:
    # Matches <version core> from SemVer 2.0.0 BNF grammar. Ex. 2.3.4, but not 2.3.4-rc
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
      when: manual  # Deploy only prod versions manually
    # Matches all of SemVer 2.0.0
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
      # Deploy rc-versions automatically
  environment:
    name: test
    url: "https://test.dysleksi.gl"

Deploy to Production:
  stage: deploy
  extends:
    - .rules:semver-core
    - .saltbert
  needs: [ "Configure Production" ]
  variables:
    SALTBERT_ORCHESTRATION: groenland.dysleksi.service-prod
    SALTBERT_URL: https://saltmaster.groenland.magentahosted.dk
  when: manual
  environment:
    name: production
    url: "https://dysleksi.gl"
