# SPDX-FileCopyrightText: 2025 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: MPL-2.0
services:

  dysleksi-web:
    user: "75200:1000"  # Override in docker-compose.override.yml if your local user is different
    container_name: dysleksi-web
    image: dysleksi:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./dev-environment/dysleksi.env
    volumes:
      - ./dysleksi/:/app:rw
      - ./log/dysleksi.log:/log/dysleksi.log:rw
      - ./dev-environment/cert:/ssl:ro
      - ./mypy.ini:/mypy.ini:ro
      - ./file-data:/upload:rw
      - idp-data:/app/idp:rw
      - staticfiles-data:/app/project/static/
    environment:
      - PULL_IDP_METADATA=true
      - MAKE_MIGRATIONS=true
      - MIGRATE=true
      - MAKEMESSAGES=true
      - CREATE_DUMMY_USERS=true
      - CREATE_DUMMY_DATA=true
      - TEST=true
      - ECHO_INTERFACE=https://localhost:8140
    networks:
      - default
      - database
    ports:
      - "8140:8443"
    depends_on:
      - dysleksi-db
    command: uvicorn project.asgi:application --host 0.0.0.0 --port 8443 --reload --ssl-certfile=/ssl/web/cert.pem --ssl-keyfile=/ssl/web/key.pem

  dysleksi-db:
    # Do not set `user` here
    container_name: dysleksi-db
    image: postgres:18
    env_file:
      - ./dev-environment/dysleksi.env
    volumes:
      - postgres-data:/var/lib/postgresql/18/data
    networks:
      - database

  dysleksi-redis:
    container_name: dysleksi-redis
    image: redis:8
    networks:
      - database

  dysleksi-idp:
    user: "1000:1000"  # Override in docker-compose.override.yml if your local user is different
    image: kenchan0130/simplesamlphp
    container_name: dysleksi-idp
    environment:
      HTTP_PORT: 8142
      SIMPLESAMLPHP_SP_ENTITY_ID: https://dysleksi-web:8140/mitid/saml/metadata/
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: https://dysleksi-web:8140/mitid/login/callback/
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: https://dysleksi-web:8140/mitid/logout/callback/
      SIMPLESAMLPHP_IDP_CERTIFICATE: /var/www/simplesamlphp/cert/selfsigned.crt
      SIMPLESAMLPHP_IDP_PRIVATEKEY: /var/www/simplesamlphp/cert/selfsigned.key
    volumes:
      - ./dev-environment/cert/idp/selfsigned.crt:/var/www/simplesamlphp/cert/server.crt:ro
      - ./dev-environment/cert/idp/selfsigned.key:/var/www/simplesamlphp/cert/server.pem:ro
      - ./dev-environment/idp/authsources.php:/var/www/simplesamlphp/config/authsources.php:ro
      - ./dev-environment/idp/saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php:ro
      - ./dev-environment/idp/ports.conf:/etc/apache2/ports.conf:ro
      - ./dev-environment/idp/site.conf:/etc/apache2/sites-available/simplesamlphp.conf:ro
    ports:
      - "8142:8142"
    networks:
      - default

  dysleksi-hosts-updater:
    container_name: dysleksi-hosts-updater
    image: bash
    volumes:
      - ./dev-environment/hosts.sh:/hosts.sh:ro
      - /etc/hosts:/hosts:rw
    command: [ "bash", "/hosts.sh" ]

  dysleksi-js-tests:
    container_name: dysleksi-js-tests
    image: node:25
    working_dir: /app
    volumes:
      - ./dysleksi/dysleksi/static/js:/app/src:ro
      - ./dysleksi/package.json:/app/package.json:ro
      - ./dysleksi/package-lock.json:/app/package-lock.json:ro
      - ./js_coverage:/app/coverage
    command: >
      sh -c "
        npm ci &&
        npx vitest run --coverage --coverage.provider=istanbul --coverage.include='/app/src/**/*.js' --coverage.reportsDirectory=/app/coverage/vitest_coverage
      "
    networks:
      - default

volumes:
  postgres-data:
  file-data:
  idp-data:
  staticfiles-data:

networks:
  default:
  database:
