# Generated by Django 6.0.2 on 2026-02-10 08:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpr', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(101000000), django.core.validators.MaxValueValidator(3112999999)], verbose_name='CPR')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('letter', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('test_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('klasse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dysleksi.class')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('dysleksi.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('dysleksi.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpr', models.BigIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(101000000), django.core.validators.MaxValueValidator(3112999999)], verbose_name='CPR')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(choices=[('question.answered', 'Question Answered'), ('question.feedback', 'Question Feedback'), ('part.complete', 'Part Complete'), ('test.complete', 'Test Complete'), ('test.cancelled', 'Test Cancelled')], max_length=32)),
                ('data', models.JSONField()),
                ('error', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dysleksi.class')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysleksi.test')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dysleksi.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysleksi.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TestPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.FileField(blank=True, null=True, upload_to='instructions')),
                ('intro', models.TextField(blank=True, null=True)),
                ('timeout', models.PositiveIntegerField()),
                ('partial_score_after', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='dysleksi.test')),
            ],
        ),
        migrations.CreateModel(
            name='PartResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_after', models.IntegerField(blank=True, null=True, verbose_name='Completion time in milliseconds')),
                ('completed', models.BooleanField(default=False)),
                ('testpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partresponses', to='dysleksi.testpart')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_practice', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('free_text', 'Free Text'), ('no_input_required', 'No Input Required')], default='multiple_choice')),
                ('timeout', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dysleksi.testpart')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Svar indtastet af testdeltageren')),
                ('answer_sound', models.FileField(blank=True, null=True, upload_to='answers', verbose_name='Svar indtalt af testdeltageren')),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('finished_after', models.IntegerField(blank=True, null=True, verbose_name='Completion time in milliseconds')),
                ('note', models.TextField(blank=True, null=True)),
                ('answer_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dysleksi.possibleanswer', verbose_name='Svar valgt af testdeltageren')),
                ('partresponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionresponses', to='dysleksi.partresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionresponse', to='dysleksi.testquestion')),
            ],
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_answers', to='dysleksi.testquestion'),
        ),
        migrations.CreateModel(
            name='InstructionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_sequence', to='dysleksi.testquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TestResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('sound', models.FileField(blank=True, null=True, upload_to='sounds')),
                ('text', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('image', ''), _negated=True), models.Q(('sound', ''), _negated=True), ('text__isnull', False), _connector='OR'), name='image_or_sound_or_text_must_be_set')],
            },
        ),
        migrations.AddField(
            model_name='testquestion',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dysleksi.testresource'),
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dysleksi.testresource'),
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dysleksi.testassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dysleksi.student')),
            ],
        ),
        migrations.AddField(
            model_name='partresponse',
            name='testresponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partresponses', to='dysleksi.testresponse'),
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='classes', to='dysleksi.teacher'),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('action', models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('fadeIn', 'Fade In'), ('fadeOut', 'Fade Out'), ('playSound', 'Play Sound'), ('highlight', 'Highlight'), ('select', 'Select')], max_length=32)),
                ('element', models.CharField(blank=True, help_text='DOM element id or logical name', max_length=64, null=True)),
                ('delay_after', models.IntegerField(default=0, help_text='Delay in milliseconds after this instruction')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='dysleksi.instructionsequence')),
                ('resource', models.ForeignKey(blank=True, help_text='Used for playSound / show image', null=True, on_delete=django.db.models.deletion.PROTECT, to='dysleksi.testresource')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('action', 'playSound'), ('resource__isnull', False)), models.Q(('action', 'playSound'), _negated=True), _connector='OR'), name='play_sound_requires_resource')],
            },
        ),
        migrations.AddConstraint(
            model_name='testassignment',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('klasse__isnull', False), _connector='OR'), name='student_or_class_must_be_set'),
        ),
    ]
