# Generated by Django 6.0.2 on 2026-02-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
