# Generated by Django 6.0.1 on 2026-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('free_text', 'Free Text')], default='multiple_choice'),
        ),
    ]
