# Generated by Django 6.0.2 on 2026-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='action',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide'), ('fadeIn', 'Fade In'), ('fadeOut', 'Fade Out'), ('showFaded', 'Show Faded'), ('playSound', 'Play Sound'), ('highlight', 'Highlight'), ('select', 'Select'), ('setText', 'Set Text'), ('setButtonSoundOnce', 'Set Button Sound Once'), ('setRepeatButtonDestination', 'Set Repeat Button Destination'), ('clickButton', 'Click Button'), ('setMarker', 'Set Marker'), ('addText', 'Add Text'), ('removeText', 'Remove Text')], max_length=32),
        ),
    ]
