# Generated by Django 6.0.2 on 2026-03-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0002_alter_instruction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='reminder_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminder_testpart', to='dysleksi.testresource'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='reminder_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminder_testquestion', to='dysleksi.testresource'),
        ),
    ]
