# Generated by Django 6.0.1 on 2026-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0002_testquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual'),
        ),
    ]
