# Generated by Django 6.0.1 on 2026-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0003_test_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('received', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(choices=[('test.answered', 'Test Answered'), ('test.complete', 'Test Complete')], max_length=32)),
                ('data', models.JSONField()),
            ],
        ),
    ]
