# Generated by Django 6.0.3 on 2026-03-23 14:06
from datetime import date

from django.db import migrations, models



def migrate_data(apps, schema_editor):
    Class = apps.get_model('dysleksi', 'Class')
    today = date.today()
    for c in Class.objects.filter(start_school_year__isnull=True):
        if today.month <= 7: # 1. halvdel af året
            years = today.year - c.start_year
            start_school_year = today.year - 1
        else:  # 2. halvdel af året
            years = today.year - c.start_year + 1
            start_school_year = today.year
        c.name = f"{years}.{c.letter}"
        c.start_school_year = start_school_year
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0003_testpart_reminder_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='class',
            name='start_school_year',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Year that this class started'),
        ),
        migrations.RunPython(
            migrate_data
        )
    ]
