# Generated by Django 6.0.3 on 2026-03-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0004_class_name_class_start_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_year',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='start_school_year',
            new_name='school_year_start',
        ),
    ]
