# Generated by Django 6.0.3 on 2026-04-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0005_remove_class_letter_remove_class_start_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('number', models.CharField(db_index=True, max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AddField(
            model_name='class',
            name='group_id',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='class',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='dysleksi.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='class',
            name='school_year_start',
            field=models.PositiveSmallIntegerField(db_index=True, default=None, null=True, verbose_name='Year that this class started'),
        ),
        migrations.AddField(
            model_name='class',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='dysleksi.institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dysleksi.institution'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='dysleksi.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('institution', 'group_id', 'school_year_start')},
        ),
    ]
