# Generated by Django 6.0.3 on 2026-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0006_institution_remove_teacher_school_class_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
