# Generated by Django 6.0.4 on 2026-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0007_test_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_choice_with_display_field', 'Multiple Choice With Display Field'), ('free_text', 'Free Text'), ('no_input_required', 'No Input Required')], default='multiple_choice'),
        ),
    ]
