# Generated by Django 6.0.4 on 2026-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0008_alter_testquestion_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresource',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='instruction',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
