# Generated by Django 6.0.4 on 2026-04-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0009_alter_testresource_options_alter_instruction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpart',
            name='intro',
        ),
    ]
