# Generated by Django 6.0.4 on 2026-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0010_remove_testpart_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='klasse',
        ),
    ]
