# Generated by Django 6.0.4 on 2026-04-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0012_alter_instruction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='continue_when_instruction_is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
