# Generated by Django 6.0.4 on 2026-04-24 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0013_testquestion_continue_when_instruction_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_proportion_limit', models.FloatField(default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('color_key', models.CharField(choices=[('gray', 'Gray'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue')], editable=False, max_length=6, unique=True)),
                ('is_default', models.BooleanField()),
                ('label_da', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('upper_proportion_limit__isnull', False), ('color_key', 'gray'), _connector='OR'), name='Only color_key: GRAY may have null upper limit')],
            },
        ),
    ]
