# Generated by Django 6.0.4 on 2026-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0014_resultcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresponse',
            name='flagged',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
