# Generated by Django 6.0.4 on 2026-05-04 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0015_testresponse_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectnessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_proportion_limit', models.FloatField(default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('color_key', models.CharField(choices=[('gray', 'Gray'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue')], editable=False, max_length=6, unique=True)),
                ('label_da', models.CharField(max_length=30)),
                ('is_default', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSpeedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_proportion_limit', models.FloatField(default=1.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('color_key', models.CharField(choices=[('gray', 'Gray'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue')], editable=False, max_length=6, unique=True)),
                ('label_da', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['upper_proportion_limit'],
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='resultcategory',
            name='Only color_key: GRAY may have null upper limit',
        ),
        migrations.DeleteModel(
            name='ResultCategory',
        ),
        migrations.AddField(
            model_name='testpart',
            name='show_normscore_speed_plot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='correctnesscategory',
            constraint=models.CheckConstraint(condition=models.Q(('upper_proportion_limit__isnull', False), ('color_key', 'gray'), _connector='OR'), name='Only color_key: GRAY may have null upper limit'),
        ),
    ]
