# Generated by Django 6.0.4 on 2026-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0016_correctnesscategory_readingspeedcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='uniid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='UniLogin UniID'),
        ),
        migrations.AddField(
            model_name='user',
            name='uniid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='UniLogin UniID'),
        ),
    ]
