# Generated by Django 6.0.5 on 2026-05-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0017_historicaluser_uniid_user_uniid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='completion_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completion_testpart', to='dysleksi.testresource'),
        ),
    ]
