# Generated by Django 6.0.5 on 2026-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0018_testpart_completion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='advance_automatically',
            field=models.BooleanField(default=False),
        ),
    ]
