# Generated by Django 6.0.5 on 2026-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0019_testquestion_advance_automatically'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPartResultsBreakdownRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.IntegerField(null=True)),
                ('upper', models.IntegerField(null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('lower'), nulls_first=True), models.OrderBy(models.F('upper'), nulls_last=True)],
            },
        ),
        migrations.AddField(
            model_name='partresponse',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.CharField(choices=[('question.displayed', 'Question Displayed'), ('question.answered', 'Question Answered'), ('question.feedback', 'Question Feedback'), ('part.complete', 'Part Complete'), ('test.complete', 'Test Complete'), ('test.cancelled', 'Test Cancelled')], max_length=32),
        ),
        migrations.AddField(
            model_name='testpart',
            name='answer_time_data_breakdown',
            field=models.ManyToManyField(related_name='answer_time_data_breakdown_parts', to='dysleksi.testpartresultsbreakdownrange'),
        ),
        migrations.AddField(
            model_name='testpart',
            name='wordcount_data_breakdown',
            field=models.ManyToManyField(related_name='wordcount_data_breakdown_parts', to='dysleksi.testpartresultsbreakdownrange'),
        ),
        migrations.AddField(
            model_name='testpart',
            name='wordlength_data_breakdown',
            field=models.ManyToManyField(related_name='wordlength_data_breakdown_parts', to='dysleksi.testpartresultsbreakdownrange'),
        ),
    ]
