# Generated by Django 6.0.5 on 2026-05-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0021_testquestion_result_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='hint_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hint_testquestion', to='dysleksi.testresource'),
        ),
    ]
