# Generated by Django 6.0.5 on 2026-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0022_testquestion_hint_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='partial_score_after',
            field=models.PositiveIntegerField(help_text='Student gets only partial score after this timeout, in milliseconds'),
        ),
        migrations.AlterField(
            model_name='testpart',
            name='reminder',
            field=models.PositiveIntegerField(default=0, help_text='Time after which to play reminder sound, in milliseconds'),
        ),
        migrations.AlterField(
            model_name='testpart',
            name='timeout',
            field=models.PositiveIntegerField(help_text='Time to complete testpart, in milliseconds'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='reminder',
            field=models.PositiveIntegerField(default=0, help_text='Time after which to play reminder sound, in milliseconds'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='timeout',
            field=models.PositiveIntegerField(default=0, help_text='Time to answer question, in milliseconds'),
        ),
    ]
