# Generated by Django 6.0.5 on 2026-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0023_alter_testpart_partial_score_after_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibleanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='correct',
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='correctness',
            field=models.CharField(choices=[('correct', 'Correct'), ('partial', 'Partial'), ('wrong', 'Wrong')], default='wrong', max_length=8),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='correctness',
            field=models.CharField(blank=True, choices=[('correct', 'Correct'), ('partial', 'Partial'), ('wrong', 'Wrong')], max_length=8, null=True),
        ),
    ]
