# Generated by Django 6.0.5 on 2026-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0024_remove_possibleanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='actual_pronunciation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='possibleanswer',
            name='correctness',
            field=models.CharField(choices=[('correct', 'Correct'), ('partial', 'Partial'), ('wrong', 'Wrong'), ('skipped', 'Skipped')], default='wrong', max_length=8),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='correctness',
            field=models.CharField(blank=True, choices=[('correct', 'Correct'), ('partial', 'Partial'), ('wrong', 'Wrong'), ('skipped', 'Skipped')], max_length=8, null=True),
        ),
    ]
