# Generated by Django 6.0.5 on 2026-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0025_questionresponse_actual_pronunciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='show_answer_time_statistics',
            field=models.BooleanField(default=False),
        ),
    ]
