# Generated by Django 6.0.5 on 2026-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0026_testpart_show_answer_time_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleanswer',
            name='index',
            field=models.IntegerField(blank=True, default=None, help_text='index where this answer should be shown in mutiple-choice questions', null=True),
        ),
    ]
