# Generated by Django 6.0.5 on 2026-06-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0027_possibleanswer_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
