# Generated by Django 6.0.6 on 2026-06-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0028_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='practice_correct_feedback_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_correct_feedback_testpart', to='dysleksi.testresource'),
        ),
        migrations.AddField(
            model_name='testpart',
            name='practice_wrong_feedback_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_wrong_feedback_testpart', to='dysleksi.testresource'),
        ),
    ]
