# Generated by Django 6.0.6 on 2026-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0029_testpart_practice_correct_feedback_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_choice_with_display_field', 'Multiple Choice With Display Field'), ('multiple_choice_match', 'Multiple Choice Match'), ('free_text', 'Free Text'), ('no_input_required', 'No Input Required')], default='multiple_choice'),
        ),
    ]
