# Generated by Django 6.0.6 on 2026-06-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0032_alter_correctnesscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partresponse',
            name='finished_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gennemførselstid i millisekunder'),
        ),
    ]
