# Generated by Django 6.0.6 on 2026-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0033_alter_partresponse_finished_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
