# Generated by Django 6.0.7 on 2026-08-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0034_testquestion_order'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
