# Generated by Django 6.1.1 on 2026-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0037_alter_class_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestassignment',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
