# Generated by Django 6.1.1 on 2026-09-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0038_historicaltestassignment_start_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestassignment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
