# Generated by Django 6.1.1 on 2026-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0039_historicaltestassignment_name_testassignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='student_subset',
            field=models.ManyToManyField(related_name='student_subset', to='dysleksi.student'),
        ),
    ]
