# Generated by Django 6.1.1 on 2026-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0040_testassignment_student_subset'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestpart',
            name='name_kl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testpart',
            name='name_kl',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
