# Generated by Django 6.0.6 on 2026-09-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysleksi', '0041_historicaltestpart_name_kl_testpart_name_kl'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestpart',
            name='reminder_interval',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Time between repeats of the reminder sound, in milliseconds. Leave empty to only play the reminder once', null=True),
        ),
        migrations.AddField(
            model_name='historicaltestquestion',
            name='reminder_interval',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Time between repeats of the reminder sound, in milliseconds. Leave empty to only play the reminder once', null=True),
        ),
        migrations.AddField(
            model_name='testpart',
            name='reminder_interval',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Time between repeats of the reminder sound, in milliseconds. Leave empty to only play the reminder once', null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='reminder_interval',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Time between repeats of the reminder sound, in milliseconds. Leave empty to only play the reminder once', null=True),
        ),
    ]
