# Generated by Django 6.0.6 on 2026-08-27 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tidspunkt')),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Brugernavn')),
                ('result', models.CharField(choices=[('success', 'Succes'), ('failure', 'Fejl')], db_index=True, max_length=8, verbose_name='Resultat')),
                ('backend', models.CharField(blank=True, max_length=255, verbose_name='Loginmetode')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-adresse')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
            ],
            options={
                'verbose_name': 'Loginforsøg',
                'verbose_name_plural': 'Loginforsøg',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tidspunkt')),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='Brugernavn')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('class_name', models.CharField(db_index=True, max_length=100, verbose_name='View')),
                ('kwargs', models.JSONField(default=dict, verbose_name='URL-parametre')),
                ('params', models.JSONField(default=dict, verbose_name='Forespørgselsparametre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bruger')),
            ],
            options={
                'verbose_name': 'Dataopslag',
                'verbose_name_plural': 'Dataopslag',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Objekt-id')),
                ('item_label', models.CharField(max_length=255, verbose_name='Objekt')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Datatype')),
                ('pageview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.pageview')),
            ],
            options={
                'verbose_name': 'Tilgået objekt',
                'verbose_name_plural': 'Tilgåede objekter',
            },
        ),
    ]
