tls:
  certificates:
    - certFile: /ssl/web/cert.pem
      keyFile: /ssl/web/key.pem

  stores:
    default:
      defaultCertificate:
        certFile: /ssl/web/cert.pem
        keyFile: /ssl/web/key.pem